# This file tells K8s how to run your backend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2 # Run 2 copies of the backend for high availability
  selector:
    matchLabels:
      app: backend # The "hook" that the Service will look for
  template: # This is the Pod (container) definition
    metadata:
      labels:
        app: backend # The "label" on the Pod
    spec:
      containers:
        - name: backend-container
          # This name is a placeholder!
          # kustomize will replace this with your real image from Docker Hub
          image: my-backend-image 
          ports:
            - containerPort: 5000 # The port Gunicorn is running on